project:
  type: website
  output-dir: docs

website:
  title: "Workshop Data Simulation with Monte Carlo Methods"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - 01_intro.qmd
      - 02_monte_carlo.qmd
      - 03_prove.qmd
      - 04_1_errors_power
      - 04_2_errors_power
      - 05_misclass_bias.qmd
      - 06_outlook.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc: true
