project:
  type: website
  output-dir: docs

website:
  title: "Workshop Data Simulation with Monte Carlo Methods"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - qmd/01_intro.qmd
      - qmd/02_monte_carlo.qmd
      - qmd/03_prove.qmd
      - qmd/04_1_errors_power
      - qmd/04_2_errors_power
      - qmd/05_misclass_bias.qmd
      - qmd/06_outlook.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc: true
