project:
  type: website
  output-dir: docs

website:
  title: "Workshop Data Simulation with Monte Carlo Methods"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme:
      dark: darkly
      light: flatly
    toc: true
